"""Changed the data type of is_ranked in EventNFS3.

Revision ID: 2fb7555f4972
Revises: ca228a52395a
Create Date: 2023-06-09 19:26:40.133792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fb7555f4972'
down_revision = 'ca228a52395a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.alter_column('is_ranked',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.alter_column('is_ranked',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
