"""Version 1.2.0.0.0 migrations

Revision ID: 3a5192c5bc73
Revises: fd5c891ede25
Create Date: 2023-06-28 09:00:37.477287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a5192c5bc73'
down_revision = 'fd5c891ede25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color_hex', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_nfs4_name'), ['name'], unique=True)

    op.create_table('event_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color_hex', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_types_name'), ['name'], unique=False)

    op.create_table('series_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('no_of_participants', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Unicode(), nullable=True),
    sa.Column('car_restriction', sa.Unicode(), nullable=True),
    sa.Column('order_in_list', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_nfs4_car_restriction'), ['car_restriction'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_nfs4_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_nfs4_no_of_participants'), ['no_of_participants'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_nfs4_order_in_list'), ['order_in_list'], unique=False)
        batch_op.create_index(batch_op.f('ix_series_nfs4_skill_level'), ['skill_level'], unique=False)

    op.create_table('tours_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('order_in_overview', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tours_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tours_nfs4_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_tours_nfs4_order_in_overview'), ['order_in_overview'], unique=False)

    op.create_table('rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('logical_elements', sa.JSON(), nullable=False),
    sa.Column('result', sa.Unicode(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rules_event_type_id'), ['event_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_order'), ['order'], unique=False)
        batch_op.create_index(batch_op.f('ix_rules_result'), ['result'], unique=False)

    op.create_table('series_nfs4_arcade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['series_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_nfs4_career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tour_id', sa.Integer(), nullable=False),
    sa.Column('order_in_tour', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['series_nfs4.id'], ),
    sa.ForeignKeyConstraint(['tour_id'], ['tours_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('series_nfs4_career', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_series_nfs4_career_order_in_tour'), ['order_in_tour'], unique=False)

    op.create_table('tracks_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('best_lap_time_event_record_id', sa.Integer(), nullable=True),
    sa.Column('best_track_time_event_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color_hex', sa.Unicode(), nullable=True),
    sa.Column('event_type_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_type_id'], ['event_types.id'], ),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_event_type_id'), ['event_type_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_name'), ['name'], unique=False)

    op.create_table('events_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('no_of_participants', sa.Integer(), nullable=False),
    sa.Column('no_of_laps', sa.Integer(), nullable=False),
    sa.Column('skill_level', sa.Unicode(), nullable=True),
    sa.Column('car_restriction', sa.Unicode(), nullable=True),
    sa.Column('is_ranked', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_nfs4_car_restriction'), ['car_restriction'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs4_is_ranked'), ['is_ranked'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs4_no_of_laps'), ['no_of_laps'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs4_no_of_participants'), ['no_of_participants'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs4_skill_level'), ['skill_level'], unique=False)

    op.create_table('events_nfs4_arcade',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order_in_overview', sa.Integer(), nullable=False),
    sa.Column('arcade_series_id', sa.Integer(), nullable=False),
    sa.Column('order_in_series', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['arcade_series_id'], ['series_nfs4_arcade.id'], ),
    sa.ForeignKeyConstraint(['id'], ['events_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events_nfs4_arcade', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_nfs4_arcade_order_in_overview'), ['order_in_overview'], unique=True)
        batch_op.create_index(batch_op.f('ix_events_nfs4_arcade_order_in_series'), ['order_in_series'], unique=True)

    op.create_table('events_nfs4_career',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('career_series_id', sa.Integer(), nullable=False),
    sa.Column('order_in_series', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('is_backwards', sa.Boolean(), nullable=False),
    sa.Column('is_mirrored', sa.Boolean(), nullable=False),
    sa.Column('is_at_night', sa.Boolean(), nullable=False),
    sa.Column('is_weather_on', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_series_id'], ['series_nfs4_career.id'], ),
    sa.ForeignKeyConstraint(['id'], ['events_nfs4.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events_nfs4_career', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_nfs4_career_order_in_series'), ['order_in_series'], unique=False)

    op.create_table('instances_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfs4_class_id', sa.Integer(), nullable=True),
    sa.Column('is_pursuit_vehicle', sa.Boolean(), nullable=False),
    sa.Column('is_unlocked_in_career', sa.Boolean(), nullable=False),
    sa.Column('is_unlocked_in_arcade', sa.Boolean(), nullable=False),
    sa.Column('acceleration', sa.Integer(), nullable=True),
    sa.Column('top_speed', sa.Integer(), nullable=True),
    sa.Column('handling', sa.Integer(), nullable=True),
    sa.Column('braking', sa.Integer(), nullable=True),
    sa.Column('overall', sa.Integer(), nullable=True),
    sa.Column('upgrade_level', sa.Integer(), nullable=True),
    sa.Column('buying_price', sa.Integer(), nullable=True),
    sa.Column('no_of_lap_records', sa.Integer(), nullable=False),
    sa.Column('no_of_track_records', sa.Integer(), nullable=False),
    sa.Column('no_of_ranked_events', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instances_racing.id'], ),
    sa.ForeignKeyConstraint(['nfs4_class_id'], ['classes_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_nfs4_acceleration'), ['acceleration'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_braking'), ['braking'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_handling'), ['handling'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_is_pursuit_vehicle'), ['is_pursuit_vehicle'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_is_unlocked_in_arcade'), ['is_unlocked_in_arcade'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_is_unlocked_in_career'), ['is_unlocked_in_career'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_no_of_lap_records'), ['no_of_lap_records'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_no_of_ranked_events'), ['no_of_ranked_events'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_no_of_track_records'), ['no_of_track_records'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_overall'), ['overall'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs4_top_speed'), ['top_speed'], unique=False)

    op.create_table('event_records_nfs4',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_added', sa.DateTime(), nullable=False),
    sa.Column('datetime_edited', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=True),
    sa.Column('no_of_event_record', sa.Integer(), nullable=False),
    sa.Column('note', sa.Unicode(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('result', sa.Unicode(), nullable=True),
    sa.Column('time_best_lap_milliseconds', sa.BigInteger(), nullable=True),
    sa.Column('time_best_lap_human_readable', sa.Unicode(), nullable=True),
    sa.Column('time_track_milliseconds', sa.BigInteger(), nullable=True),
    sa.Column('time_track_human_readable', sa.Unicode(), nullable=True),
    sa.Column('is_lap_record', sa.Boolean(), nullable=False),
    sa.Column('is_track_record', sa.Boolean(), nullable=False),
    sa.Column('maximum_speed', sa.Double(), nullable=True),
    sa.Column('is_backwards', sa.Boolean(), nullable=True),
    sa.Column('is_mirrored', sa.Boolean(), nullable=True),
    sa.Column('is_at_night', sa.Boolean(), nullable=True),
    sa.Column('is_weather_on', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['events_nfs4.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances_nfs4.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks_nfs4.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_records_nfs4', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_datetime_added'), ['datetime_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_datetime_edited'), ['datetime_edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_is_lap_record'), ['is_lap_record'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_is_track_record'), ['is_track_record'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_time_best_lap_milliseconds'), ['time_best_lap_milliseconds'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs4_time_track_milliseconds'), ['time_track_milliseconds'], unique=False)

    op.create_table('tunes_nfs4',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Integer(), nullable=False),
    sa.Column('brake_balance', sa.Integer(), nullable=False),
    sa.Column('steering_speed', sa.Integer(), nullable=False),
    sa.Column('gearbox_ratio', sa.Integer(), nullable=False),
    sa.Column('aerodynamics', sa.Integer(), nullable=False),
    sa.Column('suspension', sa.Integer(), nullable=False),
    sa.Column('tyres', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances_nfs4.id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    with op.batch_alter_table('instance_specializations', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.Unicode(), nullable=True))

    with op.batch_alter_table('instance_types', schema=None) as batch_op:
        batch_op.add_column(sa.Column('color_hex', sa.Unicode(), nullable=True))

    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_instances_is_active'), ['is_active'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instances', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_is_active'))
        batch_op.drop_column('is_active')

    with op.batch_alter_table('instance_types', schema=None) as batch_op:
        batch_op.drop_column('color_hex')

    with op.batch_alter_table('instance_specializations', schema=None) as batch_op:
        batch_op.drop_column('color_hex')

    op.drop_table('tunes_nfs4')
    with op.batch_alter_table('event_records_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_time_track_milliseconds'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_time_best_lap_milliseconds'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_is_track_record'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_is_lap_record'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_datetime_edited'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs4_datetime_added'))

    op.drop_table('event_records_nfs4')
    with op.batch_alter_table('instances_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_top_speed'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_overall'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_no_of_track_records'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_no_of_ranked_events'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_no_of_lap_records'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_is_unlocked_in_career'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_is_unlocked_in_arcade'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_is_pursuit_vehicle'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_handling'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_braking'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs4_acceleration'))

    op.drop_table('instances_nfs4')
    with op.batch_alter_table('events_nfs4_career', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_nfs4_career_order_in_series'))

    op.drop_table('events_nfs4_career')
    with op.batch_alter_table('events_nfs4_arcade', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_nfs4_arcade_order_in_series'))
        batch_op.drop_index(batch_op.f('ix_events_nfs4_arcade_order_in_overview'))

    op.drop_table('events_nfs4_arcade')
    with op.batch_alter_table('events_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_nfs4_skill_level'))
        batch_op.drop_index(batch_op.f('ix_events_nfs4_no_of_participants'))
        batch_op.drop_index(batch_op.f('ix_events_nfs4_no_of_laps'))
        batch_op.drop_index(batch_op.f('ix_events_nfs4_is_ranked'))
        batch_op.drop_index(batch_op.f('ix_events_nfs4_car_restriction'))

    op.drop_table('events_nfs4')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_name'))
        batch_op.drop_index(batch_op.f('ix_events_event_type_id'))

    op.drop_table('events')
    op.drop_table('tracks_nfs4')
    with op.batch_alter_table('series_nfs4_career', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_nfs4_career_order_in_tour'))

    op.drop_table('series_nfs4_career')
    op.drop_table('series_nfs4_arcade')
    with op.batch_alter_table('rules', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rules_result'))
        batch_op.drop_index(batch_op.f('ix_rules_order'))
        batch_op.drop_index(batch_op.f('ix_rules_event_type_id'))

    op.drop_table('rules')
    with op.batch_alter_table('tours_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tours_nfs4_order_in_overview'))
        batch_op.drop_index(batch_op.f('ix_tours_nfs4_name'))

    op.drop_table('tours_nfs4')
    with op.batch_alter_table('series_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_series_nfs4_skill_level'))
        batch_op.drop_index(batch_op.f('ix_series_nfs4_order_in_list'))
        batch_op.drop_index(batch_op.f('ix_series_nfs4_no_of_participants'))
        batch_op.drop_index(batch_op.f('ix_series_nfs4_name'))
        batch_op.drop_index(batch_op.f('ix_series_nfs4_car_restriction'))

    op.drop_table('series_nfs4')
    with op.batch_alter_table('event_types', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_types_name'))

    op.drop_table('event_types')
    with op.batch_alter_table('classes_nfs4', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_nfs4_name'))

    op.drop_table('classes_nfs4')
    # ### end Alembic commands ###
