"""Removed the is_ranked attributed from EventNFS3.

Revision ID: 59fdb8e32465
Revises: ca228a52395a
Create Date: 2023-06-10 23:52:39.367756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59fdb8e32465'
down_revision = 'ca228a52395a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.drop_index('ix_events_nfs3_is_ranked')
        batch_op.drop_column('is_ranked')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ranked', sa.INTEGER(), nullable=False))
        batch_op.create_index('ix_events_nfs3_is_ranked', ['is_ranked'], unique=False)

    # ### end Alembic commands ###
