"""Added the model for NFS3.

Revision ID: ca228a52395a
Revises: ce9af4a83a6c
Create Date: 2023-06-08 11:27:53.177866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca228a52395a'
down_revision = 'ce9af4a83a6c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes_nfs3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color_hex', sa.Unicode(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('classes_nfs3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_classes_nfs3_name'), ['name'], unique=True)

    op.create_table('events_nfs3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Unicode(), nullable=False),
    sa.Column('color_hex', sa.Unicode(), nullable=True),
    sa.Column('no_of_participants', sa.Integer(), nullable=False),
    sa.Column('no_of_laps', sa.Integer(), nullable=False),
    sa.Column('is_ranked', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_nfs3_is_ranked'), ['is_ranked'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs3_name'), ['name'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs3_no_of_laps'), ['no_of_laps'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_nfs3_no_of_participants'), ['no_of_participants'], unique=False)

    op.create_table('tracks_nfs3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('best_lap_time_event_record_id', sa.Integer(), nullable=True),
    sa.Column('best_track_time_event_record_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['locations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('instances_nfs3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nfs3_class_id', sa.Integer(), nullable=True),
    sa.Column('acceleration', sa.Integer(), nullable=False),
    sa.Column('top_speed', sa.Integer(), nullable=False),
    sa.Column('handling', sa.Integer(), nullable=False),
    sa.Column('braking', sa.Integer(), nullable=False),
    sa.Column('average', sa.Double(), nullable=False),
    sa.Column('no_of_lap_records', sa.Integer(), nullable=False),
    sa.Column('no_of_track_records', sa.Integer(), nullable=False),
    sa.Column('no_of_ranked_events', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['instances_racing.id'], ),
    sa.ForeignKeyConstraint(['nfs3_class_id'], ['classes_nfs3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instances_nfs3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instances_nfs3_acceleration'), ['acceleration'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_average'), ['average'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_braking'), ['braking'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_handling'), ['handling'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_no_of_lap_records'), ['no_of_lap_records'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_no_of_ranked_events'), ['no_of_ranked_events'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_no_of_track_records'), ['no_of_track_records'], unique=False)
        batch_op.create_index(batch_op.f('ix_instances_nfs3_top_speed'), ['top_speed'], unique=False)

    op.create_table('event_records_nfs3',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('datetime_added', sa.DateTime(), nullable=False),
    sa.Column('datetime_edited', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('no_of_event_record', sa.Integer(), nullable=False),
    sa.Column('note', sa.Unicode(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('result', sa.Unicode(), nullable=True),
    sa.Column('time_best_lap_milliseconds', sa.BigInteger(), nullable=True),
    sa.Column('time_best_lap_human_readable', sa.Unicode(), nullable=True),
    sa.Column('time_track_milliseconds', sa.BigInteger(), nullable=True),
    sa.Column('time_track_human_readable', sa.Unicode(), nullable=True),
    sa.Column('is_lap_record', sa.Boolean(), nullable=False),
    sa.Column('is_track_record', sa.Boolean(), nullable=False),
    sa.Column('maximum_speed', sa.Double(), nullable=True),
    sa.Column('is_backwards', sa.Boolean(), nullable=False),
    sa.Column('is_mirrored', sa.Boolean(), nullable=False),
    sa.Column('is_at_night', sa.Boolean(), nullable=False),
    sa.Column('is_weather_on', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events_nfs3.id'], ),
    sa.ForeignKeyConstraint(['instance_id'], ['instances_nfs3.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks_nfs3.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('event_records_nfs3', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_datetime_added'), ['datetime_added'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_datetime_edited'), ['datetime_edited'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_is_lap_record'), ['is_lap_record'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_is_track_record'), ['is_track_record'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_time_best_lap_milliseconds'), ['time_best_lap_milliseconds'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_records_nfs3_time_track_milliseconds'), ['time_track_milliseconds'], unique=False)

    op.create_table('tunes_nfs3',
    sa.Column('instance_id', sa.Integer(), nullable=False),
    sa.Column('engine', sa.Integer(), nullable=False),
    sa.Column('brake_balance', sa.Integer(), nullable=False),
    sa.Column('steering_speed', sa.Integer(), nullable=False),
    sa.Column('gearbox_ratio', sa.Integer(), nullable=False),
    sa.Column('aerodynamics', sa.Integer(), nullable=False),
    sa.Column('suspension', sa.Integer(), nullable=False),
    sa.Column('tyres', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['instance_id'], ['instances_nfs3.id'], ),
    sa.PrimaryKeyConstraint('instance_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tunes_nfs3')
    with op.batch_alter_table('event_records_nfs3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_time_track_milliseconds'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_time_best_lap_milliseconds'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_is_track_record'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_is_lap_record'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_datetime_edited'))
        batch_op.drop_index(batch_op.f('ix_event_records_nfs3_datetime_added'))

    op.drop_table('event_records_nfs3')
    with op.batch_alter_table('instances_nfs3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_top_speed'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_no_of_track_records'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_no_of_ranked_events'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_no_of_lap_records'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_handling'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_braking'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_average'))
        batch_op.drop_index(batch_op.f('ix_instances_nfs3_acceleration'))

    op.drop_table('instances_nfs3')
    op.drop_table('tracks_nfs3')
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_nfs3_no_of_participants'))
        batch_op.drop_index(batch_op.f('ix_events_nfs3_no_of_laps'))
        batch_op.drop_index(batch_op.f('ix_events_nfs3_name'))
        batch_op.drop_index(batch_op.f('ix_events_nfs3_is_ranked'))

    op.drop_table('events_nfs3')
    with op.batch_alter_table('classes_nfs3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_classes_nfs3_name'))

    op.drop_table('classes_nfs3')
    # ### end Alembic commands ###
