"""Changed the data type of name in GameState

Revision ID: ce9af4a83a6c
Revises: a7d4ebe5f6dd
Create Date: 2023-04-04 20:09:11.387112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce9af4a83a6c'
down_revision = 'a7d4ebe5f6dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.INTEGER(),
               type_=sa.Unicode(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_states', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Unicode(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
