"""Added the is_ranked attribute to EventNFS3 as boolean.

Revision ID: fd5c891ede25
Revises: 59fdb8e32465
Create Date: 2023-06-10 23:56:01.068940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fd5c891ede25'
down_revision = '59fdb8e32465'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_ranked', sa.Boolean(), nullable=True))
        batch_op.create_index(batch_op.f('ix_events_nfs3_is_ranked'), ['is_ranked'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('events_nfs3', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_nfs3_is_ranked'))
        batch_op.drop_column('is_ranked')

    # ### end Alembic commands ###
